package com.ft.domain.remittance.domain;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 *
 */
@Getter
@Setter
public class ReceiverPayload {

    /**
     * Payee information sn. Generated by the system when creating.
     */
    private String sn;

    /**
     *
     */
    private String receiveCurrency;

    /**
     * Account country
     */
    private String country;

    /**
     * Last name
     */
    private String surName;

    /**
     * First name
     */
    private String givName;

    /**
     * phone area code
     */
    private String area;

    /**
     * phone number
     */
    private String phone;

    /**
     * receiver nationality
     */
    private String nationality;

    /**
     * Bank location id
     */
    private String locationId;

    /**
     * eg: "3383"
     */
    private String bankId;

    /**
     * eg: "Gunma Bank"
     */
    private String bankName;

    /**
     * branch code BSB/IBAN etc.
     */
    private String bankBranchCode;

    /**
     *
     */
    private String bankBranchName;

    /**
     * bank account
     */
    private String accountNo;

    /**
     *
     */
    private String accountType;

    /**
     * Bank reserved mobile phone number
     */
    private String bankMobile;

    /**
     * type of certificate
     */
    private Integer idType;

    /**
     * ID number
     */
    private String idNumber;

    /**
     * Document issue date
     */
    private Date issueDate;

    /**
     *
     */
    private Boolean isExpireDateLongTerm;

    /**
     * Certificate validity
     */
    private Date expireDate;

    /**
     * Certificate issuing authority
     */
    private String licIssuAutho;

    /**
     *
     */
    private Date birthday;

    /**
     *
     */
    private String gender;

    /**
     *
     */
    private String states;

    /**
     *
     */
    private String city;

    /**
     *
     */
    private String address;

    /**
     *
     */
    private String zipCode;

    /**
     *
     */
    private String middleName;

    /**
     *
     */
    private String otherName;

    /**
     *
     */
    private Date createTime;

}
